{{- if .Values.rbac.create }}
{{- include "openlit-operator.validateValues" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openlit-operator.clusterRoleName" . }}
  labels:
    {{- include "openlit-operator.labels" . | nindent 4 }}
    component: rbac
  annotations:
    {{- include "openlit-operator.annotations" . | nindent 4 }}
rules:
# AutoInstrumentation Custom Resource permissions
- apiGroups: ["openlit.io"]
  resources: ["autoinstrumentations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["openlit.io"]
  resources: ["autoinstrumentations/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["openlit.io"]
  resources: ["autoinstrumentations/finalizers"]
  verbs: ["update"]

# Core Kubernetes resources
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

# Admission controller webhook permissions
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

# Events for logging and debugging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
{{- end }}
