# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install openlit library
RUN pip install --no-cache-dir openlit

# Expose any required ports, if necessary
EXPOSE 80

# Define default values for the environment variables
ENV GPU_APPLICATION_NAME=default
ENV GPU_ENVIRONMENT=default

# Run the script continuously
CMD ["python", "collector.py"]
