# Build stage
FROM alpine:latest AS build

# Install Python and pip
RUN apk add --no-cache python3 py3-pip

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install dependencies using pip
RUN pip install --no-cache-dir openlit

# Runtime stage
FROM alpine:latest

# Install Python only (exclude development tools)
RUN apk add --no-cache python3

# Set the working directory
WORKDIR /usr/src/app

# Copy only the necessary files from the build stage
COPY --from=build /usr/src/app /usr/src/app

# Copy installed dependencies
COPY --from=build /usr/lib/python3.9/site-packages /usr/lib/python3.9/site-packages

# Expose any required ports, if necessary
EXPOSE 80

# Run the script continuously
CMD ["python3", "collector.py"]
