apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openlit-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openlit-collector
subjects:
  - kind: ServiceAccount
    name: openlit-collector
    namespace: openlit
