# OpenLIT Operator Helm Chart Values
# This file contains all configurable options for the OpenLIT Kubernetes operator

# Global configuration
global:
  # Namespace for the operator (if not specified, will use Release.Namespace)
  namespace: ""
  # Common labels to add to all resources
  commonLabels: {}
  # Common annotations to add to all resources
  commonAnnotations: {}

# Operator image configuration
image:
  # Container image repository
  repository: ghcr.io/openlit/openlit-operator
  # Image tag (if not specified, uses Chart.AppVersion)
  tag: ""
  # Image pull policy
  pullPolicy: IfNotPresent
  # Image pull secrets
  pullSecrets: []

# Provider-specific init images (operator selects based on AutoInstrumentation CR)
providerImages:
  # OpenLIT provider image
  openlit:
    repository: ghcr.io/openlit/openlit-ai-instrumentation
    tag: ""  # Uses operator image tag by default
  # OpenLLMetry provider image  
  openllmetry:
    repository: ghcr.io/openlit/openllmetry-ai-instrumentation
    tag: ""  # Uses operator image tag by default
  # OpenInference provider image
  openinference:
    repository: ghcr.io/openlit/openinference-ai-instrumentation
    tag: ""  # Uses operator image tag by default

# Deployment configuration
deployment:
  # Number of operator replicas
  replicas: 1
  # Deployment strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  # Pod annotations
  podAnnotations: {}
  # Pod labels
  podLabels: {}
  # Security context for the pod
  podSecurityContext:
    runAsNonRoot: false  # Required for certificate management
    runAsUser: 0
    fsGroup: 0
  # Security context for the container
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false  # Allow writing certificates
    runAsNonRoot: false
    capabilities:
      drop:
      - ALL
  # Node selector
  nodeSelector: {}
  # Tolerations
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  # Affinity
  affinity: {}
  # Priority class name
  priorityClassName: ""

# Resource limits and requests
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Service account configuration
serviceAccount:
  # Create service account
  create: true
  # Service account name (if not specified, uses fullname template)
  name: ""
  # Service account annotations
  annotations: {}

# RBAC configuration
rbac:
  # Create RBAC resources
  create: true
  # Cluster role name (if not specified, uses fullname template)
  clusterRoleName: ""
  # Cluster role binding name (if not specified, uses fullname template)
  clusterRoleBindingName: ""

# Webhook configuration
webhook:
  # Webhook service configuration
  service:
    # Service name (if not specified, uses fullname template with -webhook suffix)
    name: ""
    # Service type
    type: ClusterIP
    # Service port
    port: 443
    # Target port
    targetPort: 9443
    # Service annotations
    annotations: {}
  
  # Webhook server configuration
  server:
    # Webhook port
    port: 9443
    # Webhook path
    path: "/mutate"
    # Certificate directory
    certDir: "/tmp/k8s-webhook-server/serving-certs"
  
  # Webhook behavior
  failurePolicy: Ignore  # Options: Ignore, Fail
  reinvocationPolicy: Never  # Options: Never, IfNeeded
  
  # MutatingWebhookConfiguration name (if not specified, uses fullname template)
  configName: ""

# TLS certificate configuration
tls:
  # Certificate validity in days
  validityDays: 365
  # Certificate refresh threshold in days
  refreshDays: 30
  # Secret name for storing certificates (if not specified, uses fullname template with -certs suffix)
  secretName: ""

# Health and readiness probe configuration
healthcheck:
  # Health check port
  port: 8081
  # Liveness probe
  livenessProbe:
    httpGet:
      path: /healthz
      port: health
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3
  # Readiness probe
  readinessProbe:
    httpGet:
      path: /readyz
      port: health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Observability configuration
observability:
  # Log level (debug, info, warn, error)
  logLevel: info
  # Enable self-monitoring with OpenTelemetry
  selfMonitoringEnabled: false
  # OpenTelemetry configuration for operator self-monitoring
  otel:
    # OTLP endpoint for operator logs/metrics
    endpoint: ""
    # OTLP headers
    headers: ""
    # OTLP logs endpoint (if empty, uses endpoint)
    logsEndpoint: ""
    # OTLP metrics endpoint (if empty, uses endpoint)
    metricsEndpoint: ""

# Multi-operator support
multiOperator:
  # Watch specific namespace (if empty, watches all namespaces)
  watchNamespace: ""

# Custom Resource Definition configuration
crd:
  # Install CRD (should be true for new installations)
  install: true
  # CRD annotations
  annotations: {}

# Environment variables for the operator
env:
  # Additional environment variables
  extra: []
  # Example:
  # - name: CUSTOM_VAR
  #   value: "custom-value"
  # - name: SECRET_VAR
  #   valueFrom:
  #     secretKeyRef:
  #       name: my-secret
  #       key: my-key

# Volume configuration
volumes:
  # Additional volumes
  extra: []
  # Example:
  # - name: custom-volume
  #   configMap:
  #     name: custom-config

# Volume mounts configuration
volumeMounts:
  # Additional volume mounts
  extra: []
  # Example:
  # - name: custom-volume
  #   mountPath: /custom/path

# Operator-specific configuration
operator:
  # Default init image override (if set, overrides provider-based image selection)
  defaultInitImage: ""

# CRD schema configuration (for validation)
schema:
  # Enable schema validation
  validation: true

# Instrumentation provider defaults
instrumentation:
  # Default provider (openlit, openinference, openllmetry, custom)
  defaultProvider: openlit
  # Default version
  defaultVersion: latest
  # Default image pull policy for init containers
  defaultImagePullPolicy: IfNotPresent


