export const CLIENT_EVENTS = {
	// Page
	PAGE_VISITED: "PAGE_VISITED",
	// Auth
	LOGIN: "USER_LOGIN",
	REGISTER: "USER_REGISTER",
	// Database config
	DB_CONFIG_ADD_SUCCESS: "DB_CONFIG_ADD_SUCCESS",
	DB_CONFIG_UPDATE_SUCCESS: "DB_CONFIG_UPDATE_SUCCESS",
	DB_CONFIG_ADD_FAILURE: "DB_CONFIG_ADD_FAILURE",
	DB_CONFIG_UPDATE_FAILURE: "DB_CONFIG_UPDATE_FAILURE",
	DB_CONFIG_LIST: "DB_CONFIG_LIST",
	DB_CONFIG_ACTION_CHANGE: "DB_CONFIG_ACTION_CHANGE",
	// Profile
	PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
	PROFILE_UPDATE_FAILURE: "PROFILE_UPDATE_FAILURE",
	// API KEY
	API_KEY_ADD_SUCCESS: "API_KEY_ADD_SUCCESS",
	API_KEY_ADD_FAILURE: "API_KEY_ADD_FAILURE",
	// Prompt
	PROMPT_ADD_SUCCESS: "PROMPT_ADD_SUCCESS",
	PROMPT_ADD_FAILURE: "PROMPT_ADD_FAILURE",
	PROMPT_VERSION_ADD_SUCCESS: "PROMPT_VERSION_ADD_SUCCESS",
	PROMPT_VERSION_ADD_FAILURE: "PROMPT_VERSION_ADD_FAILURE",
	PROMPT_IMPROVEMENT_RUN_SUCCESS: "PROMPT_IMPROVEMENT_RUN_SUCCESS",
	PROMPT_IMPROVEMENT_RUN_FAILURE: "PROMPT_IMPROVEMENT_RUN_FAILURE",
	PROMPT_IMPROVEMENT_SUGGESTION_ACCEPTED: "PROMPT_IMPROVEMENT_SUGGESTION_ACCEPTED",
	PROMPT_IMPROVEMENT_SUGGESTION_DECLINED: "PROMPT_IMPROVEMENT_SUGGESTION_DECLINED",
	// Vault
	VAULT_SECRET_ADD_SUCCESS: "VAULT_SECRET_ADD_SUCCESS",
	VAULT_SECRET_UPDATE_SUCCESS: "VAULT_SECRET_UPDATE_SUCCESS",
	VAULT_SECRET_ADD_FAILURE: "VAULT_SECRET_ADD_FAILURE",
	VAULT_SECRET_UPDATE_FAILURE: "VAULT_SECRET_UPDATE_FAILURE",
	// Evaluation config
	EVALUATION_CONFIG_CREATED_SUCCESS: "EVALUATION_CONFIG_CREATED_SUCCESS",
	EVALUATION_CONFIG_UPDATED_SUCCESS: "EVALUATION_CONFIG_UPDATED_SUCCESS",

	// Custom dashboard
	DASHBOARD_VIEWED: "DASHBOARD_VIEWED",
	DASHBOARD_VIEW_FAILURE: "DASHBOARD_VIEW_FAILURE",
	DASHBOARD_WIDGET_ADDED: "DASHBOARD_WIDGET_ADDED",
	DASHBOARD_WIDGET_ADD_FAILURE: "DASHBOARD_WIDGET_ADD_FAILURE",
	DASHBOARD_EXPLORER_LOADED: "DASHBOARD_EXPLORER_LOADED",
	DASHBOARD_EXPLORER_LOAD_FAILURE: "DASHBOARD_EXPLORER_LOAD_FAILURE",
	DASHBOARD_FOLDER_CREATED: "DASHBOARD_FOLDER_CREATED",
	DASHBOARD_FOLDER_CREATE_FAILURE: "DASHBOARD_FOLDER_CREATE_FAILURE",
	DASHBOARD_FOLDER_UPDATED: "DASHBOARD_FOLDER_UPDATED",
	DASHBOARD_FOLDER_UPDATE_FAILURE: "DASHBOARD_FOLDER_UPDATE_FAILURE",
	DASHBOARD_FOLDER_DELETED: "DASHBOARD_FOLDER_DELETED",
	DASHBOARD_FOLDER_DELETE_FAILURE: "DASHBOARD_FOLDER_DELETE_FAILURE",
	DASHBOARD_CREATED: "DASHBOARD_CREATED",
	DASHBOARD_CREATE_FAILURE: "DASHBOARD_CREATE_FAILURE",
	DASHBOARD_UPDATED: "DASHBOARD_UPDATED",
	DASHBOARD_UPDATE_FAILURE: "DASHBOARD_UPDATE_FAILURE",
	DASHBOARD_DELETED: "DASHBOARD_DELETED",
	DASHBOARD_DELETE_FAILURE: "DASHBOARD_DELETE_FAILURE",
	DASHBOARD_SET_MAIN_DASHBOARD: "DASHBOARD_SET_MAIN_DASHBOARD",
	DASHBOARD_SET_MAIN_DASHBOARD_FAILURE: "DASHBOARD_SET_MAIN_DASHBOARD_FAILURE",
	DASHBOARD_TOGGLE_PINNED: "DASHBOARD_TOGGLE_PINNED",
	DASHBOARD_TOGGLE_PINNED_FAILURE: "DASHBOARD_TOGGLE_PINNED_FAILURE",
	DASHBOARD_IMPORT_SUCCESS: "DASHBOARD_IMPORT_SUCCESS",
	DASHBOARD_IMPORT_FAILURE: "DASHBOARD_IMPORT_FAILURE",

	LIST_DASHBOARDS_PAGE_VISITED: "LIST_DASHBOARDS_PAGE_VISITED",
	EXPLORE_DASHBOARDS_PAGE_VISITED: "EXPLORE_DASHBOARDS_PAGE_VISITED",
	LIST_WIDGETS_PAGE_VISITED: "LIST_WIDGETS_PAGE_VISITED",

	// Fleet Hub
	FLEET_HUB_VIEWED: "FLEET_HUB_VIEWED",
	FLEET_HUB_AGENT_VIEWED: "FLEET_HUB_AGENT_VIEWED",
	FLEET_HUB_AGENT_CONFIG_SAVED: "FLEET_HUB_AGENT_CONFIG_SAVED",

	// Agents hub (applications + coding). Inventory-on-view, mirrors the
	// FLEET_HUB_VIEWED / DB_CONFIG_LIST `{count}` pattern.
	AGENTS_HUB_VIEWED: "AGENTS_HUB_VIEWED",
	CODING_AGENTS_VIEWED: "CODING_AGENTS_VIEWED",

	// Inventory counts on list page loads ("how many X exist").
	PROMPT_HUB_LIST: "PROMPT_HUB_LIST",
	RULE_ENGINE_LIST: "RULE_ENGINE_LIST",
	EVALUATION_TYPES_LIST: "EVALUATION_TYPES_LIST",

	// Observability / telemetry explorer page.
	OBSERVABILITY_PAGE_VISITED: "OBSERVABILITY_PAGE_VISITED",

	// Otter
	OTTER_CHAT_MESSAGE_SENT: "OTTER_CHAT_MESSAGE_SENT",
	OTTER_CHAT_MESSAGE_SUCCESS: "OTTER_CHAT_MESSAGE_SUCCESS",
	OTTER_CHAT_MESSAGE_FAILURE: "OTTER_CHAT_MESSAGE_FAILURE",
	OTTER_CHAT_QUERY_EXECUTED: "OTTER_CHAT_QUERY_EXECUTED",
	OTTER_CHAT_QUERY_EXECUTION_FAILURE: "OTTER_CHAT_QUERY_EXECUTION_FAILURE",
	OTTER_USAGE_PAGE_VISITED: "OTTER_USAGE_PAGE_VISITED",
	OTTER_SETTINGS_PAGE_VISITED: "OTTER_SETTINGS_PAGE_VISITED",

	// AI analysis
	AI_ANALYSIS_VIEWED: "AI_ANALYSIS_VIEWED",
	AI_ANALYSIS_RUN_SUCCESS: "AI_ANALYSIS_RUN_SUCCESS",
	AI_ANALYSIS_RUN_FAILURE: "AI_ANALYSIS_RUN_FAILURE",

	// organisation — opaque organisation_id only; PostHog Groups
	// (`organisation`) power MAO. Never send org names or emails.
	ORGANISATION_SWITCHED: "ORGANISATION_SWITCHED",
	ORGANISATION_CREATED: "ORGANISATION_CREATED",
	ORGANISATION_UPDATED: "ORGANISATION_UPDATED",
	ORGANISATION_DELETED: "ORGANISATION_DELETED",
	ORGANISATION_MEMBER_INVITED: "ORGANISATION_MEMBER_INVITED",
	ORGANISATION_MEMBER_REMOVED: "ORGANISATION_MEMBER_REMOVED",
	ORGANISATION_MEMBER_ROLE_UPDATED: "ORGANISATION_MEMBER_ROLE_UPDATED",
	ORGANISATION_INVITATION_ACCEPTED: "ORGANISATION_INVITATION_ACCEPTED",
	ORGANISATION_INVITATION_DECLINED: "ORGANISATION_INVITATION_DECLINED",
	ORGANISATION_INVITATION_CANCELLED: "ORGANISATION_INVITATION_CANCELLED",
	ORGANISATION_LIST: "ORGANISATION_LIST",

	// project — opaque project_id + organisation_id; Groups (`project`)
	// power monthly active projects. Never send project names.
	PROJECT_CREATED: "PROJECT_CREATED",
	PROJECT_SWITCHED: "PROJECT_SWITCHED",
	PROJECT_LIST: "PROJECT_LIST",

	// Page visits
	LOGIN_PAGE_VISITED: "LOGIN_PAGE_VISITED",
	REGISTER_PAGE_VISITED: "REGISTER_PAGE_VISITED",
	ONBOARDING_PAGE_VISITED: "ONBOARDING_PAGE_VISITED",
	GETTING_STARTED_PAGE_VISITED: "GETTING_STARTED_PAGE_VISITED",
	EVALUATIONS_PAGE_VISITED: "EVALUATIONS_PAGE_VISITED",
	EVALUATION_TYPES_PAGE_VISITED: "EVALUATION_TYPES_PAGE_VISITED",
	EVALUATION_TYPE_NEW_PAGE_VISITED: "EVALUATION_TYPE_NEW_PAGE_VISITED",
	EVALUATION_TYPE_EDIT_PAGE_VISITED: "EVALUATION_TYPE_EDIT_PAGE_VISITED",
	PROMPT_HUB_PAGE_VISITED: "PROMPT_HUB_PAGE_VISITED",
	PROMPT_HUB_DETAIL_PAGE_VISITED: "PROMPT_HUB_DETAIL_PAGE_VISITED",
	OTTER_CHAT_PAGE_VISITED: "OTTER_CHAT_PAGE_VISITED",
	VAULT_PAGE_VISITED: "VAULT_PAGE_VISITED",
	OPENGROUND_PAGE_VISITED: "OPENGROUND_PAGE_VISITED",
	OPENGROUND_NEW_PAGE_VISITED: "OPENGROUND_NEW_PAGE_VISITED",
	OPENGROUND_DETAIL_PAGE_VISITED: "OPENGROUND_DETAIL_PAGE_VISITED",
	CONTEXT_PAGE_VISITED: "CONTEXT_PAGE_VISITED",
	CONTEXT_NEW_PAGE_VISITED: "CONTEXT_NEW_PAGE_VISITED",
	CONTEXT_DETAIL_PAGE_VISITED: "CONTEXT_DETAIL_PAGE_VISITED",
	RULE_ENGINE_PAGE_VISITED: "RULE_ENGINE_PAGE_VISITED",
	RULE_ENGINE_DETAIL_PAGE_VISITED: "RULE_ENGINE_DETAIL_PAGE_VISITED",
	SETTINGS_PAGE_VISITED: "SETTINGS_PAGE_VISITED",
	SETTINGS_API_KEYS_PAGE_VISITED: "SETTINGS_API_KEYS_PAGE_VISITED",
	SETTINGS_EVALUATION_PAGE_VISITED: "SETTINGS_EVALUATION_PAGE_VISITED",
	SETTINGS_MANAGE_MODELS_PAGE_VISITED: "SETTINGS_MANAGE_MODELS_PAGE_VISITED",
	SETTINGS_ORGANISATION_PAGE_VISITED: "SETTINGS_ORGANISATION_PAGE_VISITED",
	DASHBOARDS_PAGE_VISITED: "DASHBOARDS_PAGE_VISITED",
	DASHBOARD_DETAIL_PAGE_VISITED: "DASHBOARD_DETAIL_PAGE_VISITED",
};

export const SERVER_EVENTS = {
	// Prompt
	PROMPT_SDK_FETCH_SUCCESS: "PROMPT_SDK_FETCH_SUCCESS",
	PROMPT_SDK_FETCH_FAILURE: "PROMPT_SDK_FETCH_FAILURE",
	// Vault
	VAULT_SECRET_SDK_FETCH_SUCCESS: "VAULT_SECRET_SDK_FETCH_SUCCESS",
	VAULT_SECRET_SDK_FETCH_FAILURE: "VAULT_SECRET_SDK_FETCH_FAILURE",
	// Evaluation
	EVALUATION_AUTO_SUCCESS: "EVALUATION_AUTO_SUCCESS",
	EVALUATION_AUTO_FAILURE: "EVALUATION_AUTO_FAILURE",

	// Otter
	OTTER_CHAT_MESSAGE_SUCCESS: "OTTER_CHAT_MESSAGE_SUCCESS",
	OTTER_CHAT_MESSAGE_FAILURE: "OTTER_CHAT_MESSAGE_FAILURE",
	AI_ANALYSIS_RUN_SUCCESS: "AI_ANALYSIS_RUN_SUCCESS",
	AI_ANALYSIS_RUN_FAILURE: "AI_ANALYSIS_RUN_FAILURE",
	PROMPT_IMPROVEMENT_SUCCESS: "PROMPT_IMPROVEMENT_SUCCESS",
	PROMPT_IMPROVEMENT_FAILURE: "PROMPT_IMPROVEMENT_FAILURE",

	// Custom dashboard
	FOLDER_CREATE_SUCCESS: "FOLDER_CREATE_SUCCESS",
	FOLDER_CREATE_FAILURE: "FOLDER_CREATE_FAILURE",
	FOLDER_UPDATE_SUCCESS: "FOLDER_UPDATE_SUCCESS",
	FOLDER_UPDATE_FAILURE: "FOLDER_UPDATE_FAILURE",
	FOLDER_DELETE_SUCCESS: "FOLDER_DELETE_SUCCESS",
	FOLDER_DELETE_FAILURE: "FOLDER_DELETE_FAILURE",

	DASHBOARD_CREATE_SUCCESS: "DASHBOARD_CREATE_SUCCESS",
	DASHBOARD_CREATE_FAILURE: "DASHBOARD_CREATE_FAILURE",
	DASHBOARD_UPDATE_SUCCESS: "DASHBOARD_UPDATE_SUCCESS",
	DASHBOARD_UPDATE_FAILURE: "DASHBOARD_UPDATE_FAILURE",
	DASHBOARD_IMPORT_SUCCESS: "DASHBOARD_IMPORT_SUCCESS",
	DASHBOARD_IMPORT_FAILURE: "DASHBOARD_IMPORT_FAILURE",
	DASHBOARD_DELETE_SUCCESS: "DASHBOARD_DELETE_SUCCESS",
	DASHBOARD_DELETE_FAILURE: "DASHBOARD_DELETE_FAILURE",
	DASHBOARD_TOGGLE_MAIN_SUCCESS: "DASHBOARD_TOGGLE_MAIN_SUCCESS",
	DASHBOARD_TOGGLE_MAIN_FAILURE: "DASHBOARD_TOGGLE_MAIN_FAILURE",
	DASHBOARD_TOGGLE_PINNED_SUCCESS: "DASHBOARD_TOGGLE_PINNED_SUCCESS",
	DASHBOARD_TOGGLE_PINNED_FAILURE: "DASHBOARD_TOGGLE_PINNED_FAILURE",
	DASHBOARD_PATCH_FAILURE: "DASHBOARD_PATCH_FAILURE",
	DASHBOARD_LAYOUT_UPDATE_SUCCESS: "DASHBOARD_LAYOUT_UPDATE_SUCCESS",
	DASHBOARD_LAYOUT_UPDATE_FAILURE: "DASHBOARD_LAYOUT_UPDATE_FAILURE",
	DASHBOARD_LAYOUT_EXPORT_SUCCESS: "DASHBOARD_LAYOUT_EXPORT_SUCCESS",
	DASHBOARD_LAYOUT_EXPORT_FAILURE: "DASHBOARD_LAYOUT_EXPORT_FAILURE",
	DASHBOARD_WIDGET_DELETE_SUCCESS: "DASHBOARD_WIDGET_DELETE_SUCCESS",
	DASHBOARD_WIDGET_DELETE_FAILURE: "DASHBOARD_WIDGET_DELETE_FAILURE",
	DASHBOARD_WIDGET_UPDATE_SUCCESS: "DASHBOARD_WIDGET_UPDATE_SUCCESS",
	DASHBOARD_WIDGET_UPDATE_FAILURE: "DASHBOARD_WIDGET_UPDATE_FAILURE",
	DASHBOARD_WIDGET_CREATE_SUCCESS: "DASHBOARD_WIDGET_CREATE_SUCCESS",
	DASHBOARD_WIDGET_CREATE_FAILURE: "DASHBOARD_WIDGET_CREATE_FAILURE",

	// Context
	CONTEXT_CREATE_SUCCESS: "CONTEXT_CREATE_SUCCESS",
	CONTEXT_CREATE_FAILURE: "CONTEXT_CREATE_FAILURE",
	CONTEXT_UPDATE_SUCCESS: "CONTEXT_UPDATE_SUCCESS",
	CONTEXT_UPDATE_FAILURE: "CONTEXT_UPDATE_FAILURE",
	CONTEXT_DELETE_SUCCESS: "CONTEXT_DELETE_SUCCESS",
	CONTEXT_DELETE_FAILURE: "CONTEXT_DELETE_FAILURE",

	// Rule Engine
	RULE_CREATE_SUCCESS: "RULE_CREATE_SUCCESS",
	RULE_CREATE_FAILURE: "RULE_CREATE_FAILURE",
	RULE_UPDATE_SUCCESS: "RULE_UPDATE_SUCCESS",
	RULE_UPDATE_FAILURE: "RULE_UPDATE_FAILURE",
	RULE_DELETE_SUCCESS: "RULE_DELETE_SUCCESS",
	RULE_DELETE_FAILURE: "RULE_DELETE_FAILURE",
	RULE_CONDITIONS_UPDATE_SUCCESS: "RULE_CONDITIONS_UPDATE_SUCCESS",
	RULE_CONDITIONS_UPDATE_FAILURE: "RULE_CONDITIONS_UPDATE_FAILURE",
	RULE_ENTITIES_CREATE_SUCCESS: "RULE_ENTITIES_CREATE_SUCCESS",
	RULE_ENTITIES_CREATE_FAILURE: "RULE_ENTITIES_CREATE_FAILURE",
	RULE_ENTITIES_DELETE_SUCCESS: "RULE_ENTITIES_DELETE_SUCCESS",
	RULE_ENTITIES_DELETE_FAILURE: "RULE_ENTITIES_DELETE_FAILURE",
	RULE_EVALUATE_SUCCESS: "RULE_EVALUATE_SUCCESS",
	RULE_EVALUATE_FAILURE: "RULE_EVALUATE_FAILURE",

	// Fleet Hub
	FLEET_HUB_CONFIG_UPDATE_SUCCESS: "FLEET_HUB_CONFIG_UPDATE_SUCCESS",
	FLEET_HUB_CONFIG_UPDATE_FAILURE: "FLEET_HUB_CONFIG_UPDATE_FAILURE",
	FLEET_HUB_TLS_CONNECTION_SUCCESS: "FLEET_HUB_TLS_CONNECTION_SUCCESS",
	FLEET_HUB_TLS_CONNECTION_FAILURE: "FLEET_HUB_TLS_CONNECTION_FAILURE",

	// Openground
	OPENGROUND_CREATE_SUCCESS: "OPENGROUND_CREATE_SUCCESS",
	OPENGROUND_CREATE_FAILURE: "OPENGROUND_CREATE_FAILURE",
	OPENGROUND_CONFIG_CREATE_SUCCESS: "OPENGROUND_CONFIG_CREATE_SUCCESS",
	OPENGROUND_CONFIG_CREATE_FAILURE: "OPENGROUND_CONFIG_CREATE_FAILURE",
	OPENGROUND_CONFIG_DELETE_SUCCESS: "OPENGROUND_CONFIG_DELETE_SUCCESS",
	OPENGROUND_CONFIG_DELETE_FAILURE: "OPENGROUND_CONFIG_DELETE_FAILURE",
	OPENGROUND_CONFIG_UPDATE_SUCCESS: "OPENGROUND_CONFIG_UPDATE_SUCCESS",
	OPENGROUND_CONFIG_UPDATE_FAILURE: "OPENGROUND_CONFIG_UPDATE_FAILURE",
	OPENGROUND_MODELS_CREATE_SUCCESS: "OPENGROUND_MODELS_CREATE_SUCCESS",
	OPENGROUND_MODELS_CREATE_FAILURE: "OPENGROUND_MODELS_CREATE_FAILURE",
	OPENGROUND_MODELS_DELETE_SUCCESS: "OPENGROUND_MODELS_DELETE_SUCCESS",
	OPENGROUND_MODELS_DELETE_FAILURE: "OPENGROUND_MODELS_DELETE_FAILURE",

	// Evaluation
	EVALUATION_CONFIG_CREATE_SUCCESS: "EVALUATION_CONFIG_CREATE_SUCCESS",
	EVALUATION_CONFIG_CREATE_FAILURE: "EVALUATION_CONFIG_CREATE_FAILURE",
	EVALUATION_CREATE_SUCCESS: "EVALUATION_CREATE_SUCCESS",
	EVALUATION_CREATE_FAILURE: "EVALUATION_CREATE_FAILURE",
	EVALUATION_FEEDBACK_SUCCESS: "EVALUATION_FEEDBACK_SUCCESS",
	EVALUATION_FEEDBACK_FAILURE: "EVALUATION_FEEDBACK_FAILURE",
	EVALUATION_TYPE_CREATE_SUCCESS: "EVALUATION_TYPE_CREATE_SUCCESS",
	EVALUATION_TYPE_CREATE_FAILURE: "EVALUATION_TYPE_CREATE_FAILURE",
	EVALUATION_TYPE_UPDATE_SUCCESS: "EVALUATION_TYPE_UPDATE_SUCCESS",
	EVALUATION_TYPE_UPDATE_FAILURE: "EVALUATION_TYPE_UPDATE_FAILURE",
	EVALUATION_TYPE_DELETE_SUCCESS: "EVALUATION_TYPE_DELETE_SUCCESS",
	EVALUATION_TYPE_DELETE_FAILURE: "EVALUATION_TYPE_DELETE_FAILURE",
	EVALUATION_LLM_RUN_SUCCESS: "EVALUATION_LLM_RUN_SUCCESS",
	EVALUATION_LLM_RUN_FAILURE: "EVALUATION_LLM_RUN_FAILURE",
	EVALUATION_OFFLINE_SUCCESS: "EVALUATION_OFFLINE_SUCCESS",
	EVALUATION_OFFLINE_FAILURE: "EVALUATION_OFFLINE_FAILURE",
	EVALUATION_OFFLINE_TYPES_SUCCESS: "EVALUATION_OFFLINE_TYPES_SUCCESS",
	EVALUATION_OFFLINE_TYPES_FAILURE: "EVALUATION_OFFLINE_TYPES_FAILURE",
	EVALUATION_OFFLINE_TYPE_CREATE_SUCCESS: "EVALUATION_OFFLINE_TYPE_CREATE_SUCCESS",
	EVALUATION_OFFLINE_TYPE_CREATE_FAILURE: "EVALUATION_OFFLINE_TYPE_CREATE_FAILURE",
	EVALUATION_OFFLINE_TYPE_UPDATE_SUCCESS: "EVALUATION_OFFLINE_TYPE_UPDATE_SUCCESS",
	EVALUATION_OFFLINE_TYPE_UPDATE_FAILURE: "EVALUATION_OFFLINE_TYPE_UPDATE_FAILURE",

	// User
	USER_ONBOARDING_COMPLETE_SUCCESS: "USER_ONBOARDING_COMPLETE_SUCCESS",
	USER_ONBOARDING_COMPLETE_FAILURE: "USER_ONBOARDING_COMPLETE_FAILURE",

	// Auto pricing
	PRICING_CONFIG_UPDATED: "PRICING_CONFIG_UPDATED",
	PRICING_AUTO_RUN_SUCCESS: "PRICING_AUTO_RUN_SUCCESS",
	PRICING_AUTO_RUN_FAILURE: "PRICING_AUTO_RUN_FAILURE",

	// Daily anonymous instance snapshot (inventory + world-total ingestion).
	// Fired once per day per install by the telemetry-snapshot cron.
	INSTANCE_TELEMETRY_SNAPSHOT: "INSTANCE_TELEMETRY_SNAPSHOT",
};
