services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.4.1
    container_name: clickhouse
    environment:
      CLICKHOUSE_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
      CLICKHOUSE_USER: ${OPENLIT_DB_USER:-default}
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ../assets/clickhouse-config.xml:/etc/clickhouse-server/config.d/custom-config.xml:ro
    ports:
      - "9000:9000"
      - "8123:8123"
    restart: always

  openlit:
    image: openlit
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: openlit
    environment:
      TELEMETRY_ENABLED: "true"
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 8123
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
      SQLITE_DATABASE_URL: file:/app/client/data/data.db
      PORT: ${PORT:-3000}
      DOCKER_PORT: ${DOCKER_PORT:-3000}
    ports:
      - "${PORT:-3000}:${DOCKER_PORT:-3000}"
    depends_on:
      - clickhouse
    volumes:
      - openlit-data:/app/client/data
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    container_name: otel-collector
    environment:
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 9000
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "55679:55679"
    depends_on:
      - clickhouse
    volumes:
      - ../assets/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    restart: always

volumes:
  clickhouse-data:
  openlit-data:
