services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.4.1
    container_name: clickhouse
    environment:
      CLICKHOUSE_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
      CLICKHOUSE_USER: ${OPENLIT_DB_USER:-default}
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ../assets/clickhouse-config.xml:/etc/clickhouse-server/config.d/custom-config.xml:ro
    ports:
      - "9000:9000"
      - "8123:8123"
    restart: always

  openlit:
    image: openlit
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        OTEL_VERSION: ${OTEL_VERSION:-v0.132.4}
        OPAMP_SUPERVISOR_VERSION: ${OPAMP_SUPERVISOR_VERSION:-v0.132.4}
        TARGETARCH: ${TARGETARCH:-arm64}
    container_name: openlit
    environment:
      TELEMETRY_ENABLED: "true"
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 8123
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
      SQLITE_DATABASE_URL: file:/app/client/data/data.db
      PORT: ${PORT:-3000}
      DOCKER_PORT: ${DOCKER_PORT:-3000}
      # OAuth Environment Variables
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-}

    env_file:
      - path: .env
        required: false
    ports:
      - "${PORT:-3000}:${DOCKER_PORT:-3000}"
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
    depends_on:
      - clickhouse
    volumes:
      - openlit-data:/app/client/data
      - ../assets/supervisor.yaml:/etc/otel/supervisor.yaml
      - ../assets/otel-collector-config.yaml:/etc/otel/otel-collector-config.yaml
    restart: always

volumes:
  clickhouse-data:
  openlit-data:
