openapi: 3.0.0
info:
  title: Get Vault API
  description: An API to fetch secret(s) by providing necessary parameters.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/vault/get-secrets:
    post:
      summary: Get Secret(s)
      description: Fetches secret(s) using the provided key or tags.
      operationId: getSecrets
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: object
              properties:
                key:
                  type: string
                  example: OPENAI_API_KEY
                tags:
                  type: array
                  items:
                    type: string
                  example: ["openai"]
      responses:
        '200':
          description: Successfully retrieved secret(s).
          content:
            application/json:
              schema:
                type: object
                properties:
                  err:
                    type: object
                    nullable: true
                  res:
                    type: object
                    example: { "OPEN_API_KEY": "OPEN_API_VALUE" }
      security:
        - apiKeyAuth: []
components:
  securitySchemes:
    apiKeyAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT